- name: create softether_dir
  become: true
  become_user: root
  file:
    path: "{{ softether_dir }}"
    state: directory
    mode: 0755

- name: download and extract vpnserver.tar.gz
  become: true
  become_user: root
  unarchive:
    remote_src: true
    src: "{{ vpnserver_src }}"
    dest: "{{ softether_dir }}"
    extra_opts:
      - --strip-components=1

- name: build vpnserver, vpncmd
  become: true
  become_user: root
  expect:
    command: make
    chdir: "{{ softether_dir }}"
    responses:
      (?i)Please choose one of above number: "1"   
